server:
  servlet:
    context-path: /api
  port: 8080
  compression:
    enabled: true
    mime-type: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
  http2:
    enabled: true
spring:
  profiles:
    active: dev
terremoto:
  sign-jwt: a123
  allowed-key: b123
  url: https://earthquake.usgs.gov/fdsnws/event/1/query?format=geojson
